services:
  astro:
    container_name: Portafolio-Astro-dev
    build:
      context: ./superior-star
      dockerfile: Dockerfile
    volumes:
      - ./superior-star:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    command: sh -c "npm install && npm run dev -- --host"

